name: Modularkayaks
favicon: null
layout_spectrum: 0.49007
typography_spectrum: 0.25542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcc2c0'
    - '#830604'
    - '#040200'
    - '#ea6576'
    - '#425e2e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.9688286227174103
purpose: []
